# Generated by Django 3.1.1 on 2020-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='totalCredits',
            field=models.IntegerField(default=10),
        ),
    ]
