# Generated by Django 3.1.3 on 2020-11-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
