# Generated by Django 3.1.3 on 2020-12-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0003_sendmailsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmailsave',
            name='amount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sendmailsave',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sendmailsave',
            name='organization',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
