# Generated by Django 3.1.3 on 2020-12-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0004_auto_20201201_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='emailReply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excelFile.sendmailsave'),
        ),
    ]
