# Generated by Django 3.1.3 on 2020-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0005_response_emailreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmailsave',
            name='responded',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
